/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyBoard {
    }
    interface MyCalculator {
    }
    interface MyHistory {
    }
    interface MyScreen {
        "content": string;
    }
}
declare global {
    interface HTMLMyBoardElement extends Components.MyBoard, HTMLStencilElement {
    }
    var HTMLMyBoardElement: {
        prototype: HTMLMyBoardElement;
        new (): HTMLMyBoardElement;
    };
    interface HTMLMyCalculatorElement extends Components.MyCalculator, HTMLStencilElement {
    }
    var HTMLMyCalculatorElement: {
        prototype: HTMLMyCalculatorElement;
        new (): HTMLMyCalculatorElement;
    };
    interface HTMLMyHistoryElement extends Components.MyHistory, HTMLStencilElement {
    }
    var HTMLMyHistoryElement: {
        prototype: HTMLMyHistoryElement;
        new (): HTMLMyHistoryElement;
    };
    interface HTMLMyScreenElement extends Components.MyScreen, HTMLStencilElement {
    }
    var HTMLMyScreenElement: {
        prototype: HTMLMyScreenElement;
        new (): HTMLMyScreenElement;
    };
    interface HTMLElementTagNameMap {
        "my-board": HTMLMyBoardElement;
        "my-calculator": HTMLMyCalculatorElement;
        "my-history": HTMLMyHistoryElement;
        "my-screen": HTMLMyScreenElement;
    }
}
declare namespace LocalJSX {
    interface MyBoard {
        "onButtonClicked"?: (event: CustomEvent<any>) => void;
    }
    interface MyCalculator {
        "onNewHistoryEntry"?: (event: CustomEvent<any>) => void;
    }
    interface MyHistory {
        "onEntryClicked"?: (event: CustomEvent<any>) => void;
    }
    interface MyScreen {
        "content"?: string;
    }
    interface IntrinsicElements {
        "my-board": MyBoard;
        "my-calculator": MyCalculator;
        "my-history": MyHistory;
        "my-screen": MyScreen;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-board": LocalJSX.MyBoard & JSXBase.HTMLAttributes<HTMLMyBoardElement>;
            "my-calculator": LocalJSX.MyCalculator & JSXBase.HTMLAttributes<HTMLMyCalculatorElement>;
            "my-history": LocalJSX.MyHistory & JSXBase.HTMLAttributes<HTMLMyHistoryElement>;
            "my-screen": LocalJSX.MyScreen & JSXBase.HTMLAttributes<HTMLMyScreenElement>;
        }
    }
}
